### ISSUE TITLE
Difference between two .ino files

### ISSUE THREAD

**Issue by graydonli** [lovyan03/M5Stack_LovyanLauncher#2]
What's the differece between LovyanLauncher.ino.m5stack_core_esp32.bin and LovyanLauncher.ino.m5stack_fire.bin?

One for normal esp32 chip, another for esp32 chip with opend psram function?

![微信截图_20190315114245](https://user-images.githubusercontent.com/9019236/54407160-adf75c00-4717-11e9-932f-8391d955ec1a.png)
![Uploading 微信截图_20190315114227.png…]()

**Comment by lovyan03** [comment]
Exactly.
It differs only in the display of memory size.
![IMG_20190315_125434](https://user-images.githubusercontent.com/42724151/54407623-e1d77f00-4721-11e9-921c-445b3af4b8a3.jpg)
